name: Build info
description: Sets common builds variables that are needed for other build steps

outputs:
  PYTHON_VERSIONS:
    description: |
      Python versions for which tests will be run.
      The oldest version is replaced by the literal "min" and
      the newest is replaced by the literal "max".
    value: '["min", "3.9", "3.10", "3.11", "3.12", "max"]'
  PYTHON_MIN_VERSION:
    description: Oldest version of Python supported by Streamlit
    value: "3.8"
  PYTHON_MAX_VERSION:
    description: Latest version of Python supported by Streamlit
    value: "3.13"

runs:
  using: composite
  steps:
    - name: Configure Python version info
      shell: bash
      run: echo "Values are directly set in outputs"
